### ISSUE TITLE
Scrapperapi issue

### ISSUE THREAD

**Issue by NaveedMunsif** [alvaro-escalante/google-index-checker#11]
I am facing the issue, when I run the NPM start, `There is a problem connecting to Scraperapi, please try again later`.  When I typed npm start, 
google-index-checker@3.3.0 start
 node google-index-checker.js   
There is a problem connecting to Scraperapi, please try again later

**Comment by yourNameIsGood** [comment]
Most likely it is a network connection issue. I had the same problem and solved it by running the script on cloud.
