### ISSUE TITLE
Script ending prematurely and not pausing at various places / running very very slow.

### ISSUE THREAD

**Issue by kkohlmann55** [alvaro-escalante/google-index-checker#6]
Hi, 

I love this script and it was working fine until I got up to 20,000 pages (out of 444,000) and then it locked up.

Now, whenever I run the URLs again (I reduced the file down to 335,000...it runs and then completes around 2,xxx URLs as if it's completed all its checks.

Can you please advise as I purchased scraperapi's starter plan and am trying to use it ASAP?

Not sure if the below message is a warning or an actual error message, but I included it below.

Lastly, I'm running on Windows 10, with the latest version of node.js installed...

Thank you!

Checking: 211/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2501-pn-34-33250.rfq 200 Not Indexed
Checking: 212/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2441-pn-943.rfq 200 Not Indexed
(node:33132) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at Object.runRequest (E:\google-index-checker\google-index-checker-master\google-index-checker.js:120:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 16)
    at async Object.getUrls (E:\google-index-checker\google-index-checker-master\google-index-checker.js:75:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:33132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Checking: 213/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2501-tm-34-31250.rfq 200 Not Indexed
Checking: 214/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2501-r2-903.rfq 200 Not Indexed
Checking: 215/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2501-t-943.rfq 200 Not Indexed
Checking: 216/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2501-pn-34-32251.rfq 200 Not Indexed
Checking: 217/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2501-en-34-32252.rfq 200 Not Indexed
Checking: 218/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2501-t-34-33250.rfq 200 Not Indexed
Checking: 219/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2501-t-34-31250.rfq 200 Not Indexed
Checking: 220/347815 https://abccompany.com/datasearch/itt-grinnell-valves/10-2501-r2-34-32251.rfq 200 Not Indexed

**Comment by alvaro-escalante** [comment]
Hi kkohlmann55, Scrapper API has done that to us form time to time, I will review the error handling, now that we have `Promise.allSettled()` so we can recycle that error and not block the script

**Comment by alvaro-escalante** [comment]
I have changed it to `Promise.allSettled()` so it should't be any more Unhandled promises rejections. Let me know if you encounterd any problems.
