### ISSUE TITLE
1 Url saved in result.csv

### ISSUE THREAD

**Issue by dx123d** [alvaro-escalante/google-index-checker#7]
Hello, I tried provided code. It is working perfectly and displaying correct status. But it saved only 1 Url in result.csv file whereas I provided bulk urls. Even code did check status for each provided Url in terminal but seems it is over writing in result.csv with last result . Thank you for this amazing code.

**Comment by alvaro-escalante** [comment]
Yes, thanks for spotting the issue. Fixed by adding the appending flag to the write stream.
